### ISSUE TITLE
Пожелания! 

### ISSUE THREAD

**Issue by dmitriimail** [gaisindanil/Gms#10]
Прошу добавить ряд улучшений! если это возможно!

1. Сделать возможность, что бы при нажатии, на главной странице на картинку сервера, открывалась ссылка с этим сервером
2. Добавить статистику по серверам, что бы пользователь мог видеть онлайн своего сервера
3. Сделать расширенный поиск по серверам и игрокам / аналогично в админке/ поиск по серверу и юзеру!
4. Добавить систему скидок, и внедрить ее в админку!
5. Изменить модуль покупок услуг, сделайте по аналогии как у SVV

**Comment by gaisindanil** [comment]
Здравствуйте, спасибо, постараемся учесть Ваши пожелания в следующих выпусках!
