### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by datguyjaydee** [gaisindanil/Gms#22]
Несколько ошибок которые я нашел:
1. Ошибка с пагинацией
![1234](https://user-images.githubusercontent.com/25561333/210182767-885630da-7b5c-44a2-927a-f5a0a6afb47e.jpg)
2. Услуги не добавляются в админ панели (при нажатии на кнопку ничего не происходит)
3. В админ-панели не ищет сервера, кроме cs 1.6 (может мне так повезло)
4. По ссылке /?game=cs, /?game=css, и тд. (или любой другой) не работает пагинация вообще. 
5. По ссылке: /user/servers?page= в личном кабинете не отображаются карты
6. В личном кабинете некоторые сервера работают, а информации о них нет
 ![serverlk](https://user-images.githubusercontent.com/25561333/210361896-a9771a75-4ef8-4811-8cf7-ae68f290534b.png)

Пожелания:
Сделать "защиту" от неправильного ввода IP и ПОРТа, иначе "вешается" крон в 500 ошибку и потом пол дня пытаешься разобраться в чем дело

**Comment by gaisindanil** [comment]
Здравствуйте, спасибо, в следующим выпуске исправим данные ошибки.
