### ISSUE TITLE
subfolder

### ISSUE THREAD

**Issue by Sh4d0wless** [gaisindanil/Gms#23]
hello
i instaled gms in subfolder like http://site.com/gms/
not subdomain
and it does not work
is there there any instruction for subfolder?

httpd error_log
[Fri Jul 07 11:27:48.936674 2023] [php7:emerg] [pid 42745] [client MYIP:56351] PHP Parse error:  syntax error, unexpected 'View' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /srv/www/htdocs/gms/core/BaseController.php on line 7

**Comment by gaisindanil** [comment]
Thanks for the feedback, we'll fix it in the next release!
