### ISSUE TITLE
install GMS

### ISSUE THREAD

**Issue by SmOkEnksp** [gaisindanil/Gms#5]
when i try to install GMS i get error:

Fatal error: Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/gms/install/index.php:85 Stack trace: #0 /var/www/gms/install/index.php(85): PDO->__construct('mysql:host=DB_H...', 'DB_USER', 'DB_PASSWORD', Array) #1 {main} Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/gms/install/index.php:85 Stack trace: #0 /var/www/gms/install/index.php(85): PDO->__construct('mysql:host=DB_H...', 'DB_USER', 'DB_PASSWORD', Array) #1 {main} thrown in /var/www/gms/install/index.php on line 85

please help.

**Comment by gaisindanil** [comment]
У вас какая версия php стоит?

**Comment by SmOkEnksp** [comment]
> У вас какая версия php стоит?

7.0, но пару часов назад, каким то чудным образом у меня все же прошла установка. Однако, неработало половина функционала, в логах ошибки:
[Sun Nov 08 06:41:43.537889 2020] [:error] [pid 174560] [client 95.ххх.ххх.ххх:37726] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'hash' doesn't have a default value in /var/www/gms/controllers/UserController.php:285\nStack trace:\n#0 /var/www/gms/controllers/UserController.php(285): PDO->exec('INSERT INTO ga_...')\n#1 /var/www/gms/core/Route_class.php(50): UserController->actionSignup()\n#2 /var/www/gms/index.php(25): Route->__construct()\n#3 {main}\n  thrown in /var/www/gms/controllers/UserController.php on line 285, referer: http://gms.ххх.ru/user/signup
По предварительным данным, установка(возможно) завершилась успешно т.к. обновил mysql до версии 8.0.
Сейчас же пока что снес панель, что бы подождать вашего ответа и установить заного.

**Comment by gaisindanil** [comment]
Попробуйте сменить версию mysql базы данных на 5.7
