### ISSUE TITLE
Бусты

### ISSUE THREAD

**Issue by dmitriimail** [gaisindanil/Gms#6]
1. При повторном взятии буста (к примеру 10штук) одним и тем же  клиентом, прибавляется +1, вместо 10
2. Настроить правильный запрос в платежную систему unitpay, а именно пополнение баланса в личном кабинете (на данный момент не работает), если покупаем услугу на прямую, то ссылка формируется правильно!
3. По возможности сделать вывод услуги выделением цвета, на главную страницу - вот пример http://gmspro.mastercs.ru/

**Comment by gaisindanil** [comment]
Спасибо за Ваш запрос, в следующем выпуске мы обязательно это исправим!

**Comment by gaisindanil** [comment]
Данные ошибки были исправлены.
